// frontend/src/Users.svelte
<script >
import axios from 'axios';
import {
    Card,
    CardTitle,
    CardActions,
    Button,
    Col,
} from 'svelte-materialify';
import {
    onMount
} from 'svelte';
import {
    get
} from 'svelte/store';
let users = [];

function getUsers() {
    axios.get(`http://localhost:3000/api/users`)
        .then((res) => {
            users = res.data;
        });
};

function removeUser(userID) {
    const path = `http://localhost:3000/api/users/${userID.user._id}`;
    axios.delete(path)
        .then(() => {
            console.log('Success');
            getUsers();
        })
        .catch((error) => {
            console.error(error);
            getUsers();
        });
};

onMount(async () => {
    getUsers();
});
</script>
<h2>Users</h2>

<div id="header" style="width:20em;margin-left:auto;margin-right:auto;margin-top:10px;text-align:center">
<Col>
{#each users as user}
<div style="margin-top:8px;">
<Card>
    <CardTitle>{user.username}</CardTitle>
    <CardActions>
        <Button on:click={removeUser({user})} >Remove</Button>
    </CardActions>
</Card>
</div>
{/each}
</Col>
</div>

// frontend-vue/src/components/Users.vue
<template>
<div style="width:20em;margin-left:auto;margin-right:auto;text-align:center">
    <div style="margin-top:10px" v-for="user in users" v-bind:key="user.username">
        <v-card class="mx-auto">
            <v-list-item>
                <p> {{user.username}}</p>
            </v-list-item>
            <v-card-actions>
                <v-btn>
                    Click me!
                </v-btn>
            </v-card-actions>
        </v-card>
    </div>
</div>
</template>

<script>
export default {
    methods: {
        getUsers() {
            this.axios.get('/users').then((res) => {
                this.users = res.data;
            })
        },
    },
    name: "Users",
    data() {
        return {
            users: null
        }
    },
    mounted() {
        this.getUsers();
    }
}
</script>
